name: PipxUbuntuBug

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # pipx on ubuntu is an issue
        os: [ubuntu-latest, macos-latest, windows-latest]
        # os: [macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install test dependencies
      run: |
        pip install pipx
        pipx install cowsay
        pipx ensurepath
        pipx --version
        echo $PIPX_HOME
        echo $PIPX_BIN_DIR
    # Need a new shell so that ensurepath takes
    - name: Test
      run: |
        echo $PATH
        cowsay
